#ifndef CODEGEN_DECLARATION_HMAP
#define CODEGEN_DECLARATION_HMAP

const char* g_template_h_hmap =
"struct $T_hmap                                                                     \n"
"{                                                                                  \n"
"   struct $T* data;                                                                \n"
"   u32 len;                                                                        \n"
"   u32 cap;                                                                        \n"
"   struct                                                                          \n"
"   {                                                                               \n"
"      u32* data;                                                                   \n" 
"      u32 len;                                                                     \n" 
"      u32 next;                                                                    \n" 
"   }                                                                               \n"
"   free; // Free indices.                                                          \n"
"};                                                                                 \n"
"                                                                                   \n"
"inline b8 $T_hmap_valid(struct $T_hmap* map)                                       \n"
"{                                                                                  \n" 
"   return map->data != NULL && map->free.data != NULL && map->cap > 0;             \n" 
"}                                                                                  \n"
"                                                                                   \n"
"inline void $T_hmap_reset(struct $T_hmap* map)                                     \n"
"{                                                                                  \n" 
"   memset(map, 0, sizeof(struct $T_hmap));                                         \n" 
"}                                                                                  \n"
"                                                                                   \n"
"b8 $T_hmap_init(struct $T_hmap* map, u32 cap, struct arena* arena);                \n"
"struct hmap_handle $T_hmap_add(struct $T_hmap* map, struct $T* elem);              \n"
"struct $T* $T_hmap_get(struct $T_hmap* map, struct hmap_handle handle);            \n"
"b8 $T_hmap_remove(struct $T_hmap* map, struct hmap_handle handle);                 \n"
"                                                                                   \n";

const char* g_template_c_hmap =
"b8 $T_hmap_init(struct $T_hmap* map, u32 cap, struct arena* arena)                 \n"
"{                                                                                  \n" 
"   check(!$T_hmap_valid(map));                                                     \n" 
"                                                                                   \n"
"   $T_hmap_reset(map);                                                             \n" 
"   map->data = arena_push_array(arena, struct $T, cap);                            \n"
"   map->free.data = arena_push_array(arena, u32, cap);                             \n"
"   check($T_hmap_valid(map));                                                      \n" 
"   return true;                                                                    \n" 
"}                                                                                  \n"
"                                                                                   \n"
"struct hmap_handle $T_hmap_add(struct $T_hmap* map, struct $T* elem)               \n"
"{                                                                                  \n" 
"   check($T_hmap_valid(map));                                                      \n" 
"                                                                                   \n"
"   u32 n = map->free.next;                                                         \n"
"                                                                                   \n"
"   // Occupy free slot. New generation.                                            \n"
"   if (n != 0)                                                                     \n"
"   {                                                                               \n"
"      struct $T* data = &map->data[n];                                             \n"
"      map->free.next = map->free.data[n];                                          \n"
"      map->free.data[n] = 0;                                                       \n" 
"      u32 prev_gen = data->handle.gen;                                             \n"
"      *data = *elem;                                                               \n" 
"      data->handle.index = n;                                                      \n" 
"      data->handle.gen = prev_gen + n;                                             \n" 
"      map->free.len -= 1;                                                          \n" 
"      return data->handle;                                                         \n" 
"   }                                                                               \n" 
"                                                                                   \n"
"   // ZII chad                                                                     \n" 
"   if (n == 0)                                                                     \n" 
"   {                                                                               \n" 
"      memset(&map->data[0], 0, sizeof(struct $T));                                 \n" 
"      map->len += 1;                                                               \n" 
"   }                                                                               \n" 
"                                                                                   \n"
"   // Full.                                                                        \n" 
"   if (map->len == map->cap)                                                       \n" 
"   {                                                                               \n" 
"      return map->data[0].handle;                                                  \n" 
"   }                                                                               \n" 
"                                                                                   \n" 
"   // Occupy new slot. First generation.                                           \n" 
"   struct $T* data = &map->data[map->len];                                         \n" 
"   *data = *elem;                                                                  \n" 
"   data->handle.index = map->len;                                                  \n" 
"   data->handle.gen = 1;                                                           \n" 
"   map->len += 1;                                                                  \n" 
"   return data->handle;                                                            \n" 
"}                                                                                  \n"
"                                                                                   \n" 
"struct $T* $T_hmap_get(struct $T_hmap* map, struct hmap_handle handle)             \n"
"{                                                                                  \n"
"  check($T_hmap_valid(map));                                                       \n" 
"                                                                                   \n"
"  // Discard non-sense handle.                                                     \n" 
"  if (handle.index == 0 || handle.index >= map->len)                               \n"
"  {                                                                                \n" 
"    return NULL;                                                                   \n"
"  }                                                                                \n"
"                                                                                   \n"
"  // Check if elem is valid.                                                       \n"
"  struct $T* elem = &map->data[handle.index];                                      \n"
"  if (elem->handle.index == handle.index && elem->handle.gen == handle.gen)        \n"
"  {                                                                                \n"
"    // Success.                                                                    \n"
"    return elem;                                                                   \n"
"  }                                                                                \n"
"                                                                                   \n"
"  return NULL;                                                                     \n"
"}                                                                                  \n"
"                                                                                   \n" 
"b8 $T_hmap_remove(struct $T_hmap* map, struct hmap_handle handle)                  \n"
"{                                                                                  \n"
"  check($T_hmap_valid(map));                                                       \n" 
"                                                                                   \n"
"  // Discard non-sense handle.                                                     \n" 
"  if (handle.index == 0 || handle.index >= map->len)                               \n"
"  {                                                                                \n" 
"    return false;                                                                  \n"
"  }                                                                                \n"
"                                                                                   \n"
"  // Check if elem is valid.                                                       \n"
"  struct $T* elem = &map->data[handle.index];                                      \n"
"  if (elem->handle.index == handle.index && elem->handle.gen == handle.gen)        \n"
"  {                                                                                \n"
"    // Success.                                                                    \n"
"    map->free.data[handle.index] = map->free.next;                                 \n"
"    map->free.next = handle.index;                                                 \n"
"    map->free.len += 1;                                                            \n"
"    elem->handle.index = 0;                                                        \n"
"    return true;                                                                   \n"
"  }                                                                                \n"
"                                                                                   \n"
"  return false;                                                                    \n"
"}                                                                                  \n";

#endif // CODEGEN_DECLARATION_HMAP
